-- ASTON MARTIN
['amdbx'] = {
    ['name'] = 'Aston Martin DBX Carbon Edition',
    ['brand'] = 'Aston Martin',
    ['model'] = 'amdbx',
    ['price'] = 218000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `amdbx`,
    ['shop'] = 'pdm',
},
['ast'] = {
    ['name'] = '2013 Aston Martin Vanquish',
    ['brand'] = 'Aston Martin',
    ['model'] = 'ast',
    ['price'] = 300000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `ast`,
    ['shop'] = 'pdm',
},

-- VOLKSWAGEN
['golfgti7'] = {
    ['name'] = '2015 Volkswagen Golf GTI MK7',
    ['brand'] = 'Volkswagen',
    ['model'] = 'golfgti7',
    ['price'] = 29000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `golfgti7`,
    ['shop'] = 'pdm',
},
['passat'] = {
    ['name'] = '2016 Volkswagen Passat B8',
    ['brand'] = 'Volkswagen',
    ['model'] = 'passat',
    ['price'] = 24000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `passat`,
    ['shop'] = 'pdm',
},
['vwr'] = {
    ['name'] = 'Volkswagen Scirocco R 2011',
    ['brand'] = 'Volkswagen',
    ['model'] = 'vwr',
    ['price'] = 30000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `vwr`,
    ['shop'] = 'pdm',
},
['amarok'] = {
    ['name'] = '2018 Volkswagen Amarok V6',
    ['brand'] = 'Volkswagen',
    ['model'] = 'amarok',
    ['price'] = 38000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `amarok`,
    ['shop'] = 'pdm',
},
['golf8gti'] = {
    ['name'] = 'Volkswagen Golf 8 gti',
    ['brand'] = 'Volkswagen',
    ['model'] = 'golf8gti',
    ['price'] = 31000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `golf8gti`,
    ['shop'] = 'pdm',
},
-- MASERATI
['levante'] = {
    ['name'] = 'Maserati Levante',
    ['brand'] = 'Maserati',
    ['model'] = 'levante',
    ['price'] = 70000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `levante`,
    ['shop'] = 'pdm',
},

-- MAZDA
['84rx7k'] = {
    ['name'] = '1984 Mazda RX-7 Stanced Version',
    ['brand'] = 'Mazda',
    ['model'] = '84rx7k',
    ['price'] = 30000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `84rx7k`,
    ['shop'] = 'pdm',
},
['dragfd'] = {
    ['name'] = '2002 Mazda RX-7 FD Drag',
    ['brand'] = 'Mazda',
    ['model'] = 'dragfd',
    ['price'] = 40000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `dragfd`,
    ['shop'] = 'pdm',
},
['fc3s'] = {
    ['name'] = 'Mazda RX7 FC3S',
    ['brand'] = 'Mazda',
    ['model'] = 'fc3s',
    ['price'] = 25000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `fc3s`,
    ['shop'] = 'pdm',
},
['majfd'] = {
    ['name'] = 'Mazda RX-7 FD',
    ['brand'] = 'Mazda',
    ['model'] = 'majfd',
    ['price'] = 30000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `majfd`,
    ['shop'] = 'pdm',
},
['miata3'] = {
    ['name'] = '1989 Mazda Miata NA',
    ['brand'] = 'Mazda',
    ['model'] = 'miata3',
    ['price'] = 20000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `miata3`,
    ['shop'] = 'pdm',
},
['na6'] = {
    ['name'] = 'Mazda MX-5 Miata (NA6C)',
    ['brand'] = 'Mazda',
    ['model'] = 'na6',
    ['price'] = 22000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `na6`,
    ['shop'] = 'pdm',
},

-- MCLAREN
['mcst'] = {
    ['name'] = '2020 McLaren Speedtail',
    ['brand'] = 'McLaren',
    ['model'] = 'mcst',
    ['price'] = 2000000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `mcst`,
    ['shop'] = 'pdm',
},

-- MERCEDES
['amggtrr20'] = {
    ['name'] = '2020 Mercedes-Benz AMG GT-R Roadster',
    ['brand'] = 'Mercedes-Benz',
    ['model'] = 'amggtrr20',
    ['price'] = 250000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `amggtrr20`,
    ['shop'] = 'pdm',
},
['c6320'] = {
    ['name'] = '2020 Mercedes-AMG C63s',
    ['brand'] = 'Mercedes-Benz',
    ['model'] = 'c6320',
    ['price'] = 120000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `c6320`,
    ['shop'] = 'pdm',
},
['G65'] = {
    ['name'] = '2013 Mercedes-Benz G65 AMG',
    ['brand'] = 'Mercedes-Benz',
    ['model'] = 'G65',
    ['price'] = 150000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `G65`,
    ['shop'] = 'pdm',
},
['e400'] = {
    ['name'] = '2019 Mercedes-Benz E400 Coupe 4matic (C238)',
    ['brand'] = 'Mercedes-Benz',
    ['model'] = 'e400',
    ['price'] = 90000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `e400`,
    ['shop'] = 'pdm',
},
['gl63'] = {
    ['name'] = 'Mercedes-Benz GL63 AMG',
    ['brand'] = 'Mercedes-Benz',
    ['model'] = 'gl63',
    ['price'] = 85000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `gl63`,
    ['shop'] = 'pdm',
},
['mbc63'] = {
    ['name'] = '2012 Mercedes-Benz C63 AMG Coupe Black Series',
    ['brand'] = 'Mercedes-Benz',
    ['model'] = 'mbc63',
    ['price'] = 110000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `mbc63`,
    ['shop'] = 'pdm',
},
['s500w222'] = {
    ['name'] = '2014 Mercedes-Benz S500 W222',
    ['brand'] = 'Mercedes-Benz',
    ['model'] = 's500w222',
    ['price'] = 130000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `s500w222`,
    ['shop'] = 'pdm',
},
['sl500'] = {
    ['name'] = '1995 Mercedes-Benz SL500',
    ['brand'] = 'Mercedes-Benz',
    ['model'] = 'sl500',
    ['price'] = 40000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `sl500`,
    ['shop'] = 'pdm',
},
['v250'] = {
    ['name'] = 'Mercedes-Benz V-class 250 Bluetec LWB',
    ['brand'] = 'Mercedes-Benz',
    ['model'] = 'v250',
    ['price'] = 70000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `v250`,
    ['shop'] = 'pdm',
},

-- MITSUBISHI
['cp9a'] = {
    ['name'] = 'Mitsubishi Lancer Evo VI T.M.E (CP9A)',
    ['brand'] = 'Mitsubishi',
    ['model'] = 'cp9a',
    ['price'] = 35000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `cp9a`,
    ['shop'] = 'pdm',
},
['fto'] = {
    ['name'] = 'Mitsubishi FTO GP Version-R',
    ['brand'] = 'Mitsubishi',
    ['model'] = 'fto',
    ['price'] = 25000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `fto`,
    ['shop'] = 'pdm',
},

-- NISSAN
['180sx'] = {
    ['name'] = 'Nissan 180SX Type-X',
    ['brand'] = 'Nissan',
    ['model'] = '180sx',
    ['price'] = 25000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `180sx`,
    ['shop'] = 'pdm',
},
['gtr'] = {
    ['name'] = '2017 Nissan GTR',
    ['brand'] = 'Nissan',
    ['model'] = 'gtr',
    ['price'] = 120000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `gtr`,
    ['shop'] = 'pdm',
},
['gtrc'] = {
    ['name'] = '2017 R35 Nissan GTR Convertible',
    ['brand'] = 'Nissan',
    ['model'] = 'gtrc',
    ['price'] = 130000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `gtrc`,
    ['shop'] = 'pdm',
},
['maj350'] = {
    ['name'] = 'Nissan Fairlady Z Z33',
    ['brand'] = 'Nissan',
    ['model'] = 'maj350',
    ['price'] = 30000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `maj350`,
    ['shop'] = 'pdm',
},
['nis15'] = {
    ['name'] = 'Nissan Silvia S15 Spec-R',
    ['brand'] = 'Nissan',
    ['model'] = 'nis15',
    ['price'] = 30000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `nis15`,
    ['shop'] = 'pdm',
},
['nissantitan17'] = {
    ['name'] = '2017 Nissan Titan Warrior',
    ['brand'] = 'Nissan',
    ['model'] = 'nissantitan17',
    ['price'] = 40000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `nissantitan17`,
    ['shop'] = 'pdm',
},
['ns350'] = {
    ['name'] = 'Nissan 350z Stardast',
    ['brand'] = 'Nissan',
    ['model'] = 'ns350',
    ['price'] = 35000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `ns350`,
    ['shop'] = 'pdm',
},
['nzp'] = {
    ['name'] = 'Nissan 370z "Pandem"',
    ['brand'] = 'Nissan',
    ['model'] = 'nzp',
    ['price'] = 40000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `nzp`,
    ['shop'] = 'pdm',
},
['s14'] = {
    ['name'] = '1998 Nissan Silvia K',
    ['brand'] = 'Nissan',
    ['model'] = 's14',
    ['price'] = 28000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `s14`,
    ['shop'] = 'pdm',
},
['Safari97'] = {
    ['name'] = '1997 Nissan Patrol Super Safari Y60',
    ['brand'] = 'Nissan',
    ['model'] = 'Safari97',
    ['price'] = 30000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `Safari97`,
    ['shop'] = 'pdm',
},
['skyline'] = {
    ['name'] = 'Nissan Skyline GT-R (BNR34)',
    ['brand'] = 'Nissan',
    ['model'] = 'skyline',
    ['price'] = 50000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `skyline`,
    ['shop'] = 'pdm',
},
['z32'] = {
    ['name'] = 'Nissan 300ZX Z32',
    ['brand'] = 'Nissan',
    ['model'] = 'z32',
    ['price'] = 30000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `z32`,
    ['shop'] = 'pdm',
},

-- PEUGEOT
['twingo'] = {
    ['name'] = 'Peugeot Twingo',
    ['brand'] = 'Peugeot',
    ['model'] = 'twingo',
    ['price'] = 10000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `twingo`,
    ['shop'] = 'pdm',
},

-- PORSCHE
['maj935'] = {
    ['name'] = '1978 Porsche 935 Moby Dick',
    ['brand'] = 'Porsche',
    ['model'] = 'maj935',
    ['price'] = 350000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `maj935`,
    ['shop'] = 'pdm',
},
['pcs18'] = {
    ['name'] = '2018 Porsche Cayenne S',
    ['brand'] = 'Porsche',
    ['model'] = 'pcs18',
    ['price'] = 80000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `pcs18`,
    ['shop'] = 'pdm',
},
['taycan'] = {
    ['name'] = '2020 Porsche Taycan Turbo S',
    ['brand'] = 'Porsche',
    ['model'] = 'taycan',
    ['price'] = 150000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `taycan`,
    ['shop'] = 'pdm',
},
['718caymans'] = {
    ['name'] = 'Porsche 718 Cayman S',
    ['brand'] = 'Porsche',
    ['model'] = '718caymans',
    ['price'] = 80000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `718caymans`,
    ['shop'] = 'pdm',
},
['cgt'] = {
    ['name'] = '2003 Porsche Carrera GT (980)',
    ['brand'] = 'Porsche',
    ['model'] = 'cgt',
    ['price'] = 500000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `cgt`,
    ['shop'] = 'pdm',
},

-- PEUGEOT
['yPG205t16A'] = {
    ['name'] = 'Peugeot 205 Rally',
    ['brand'] = 'Peugeot',
    ['model'] = 'yPG205t16A',
    ['price'] = 15000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `yPG205t16A`,
    ['shop'] = 'pdm',
},
['yPG205t16B'] = {
    ['name'] = 'Peugeot 205 Turbo 16',
    ['brand'] = 'Peugeot',
    ['model'] = 'yPG205t16B',
    ['price'] = 18000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `yPG205t16B`,
    ['shop'] = 'pdm',
},

-- RANGEROVER
['rrevoque'] = {
    ['name'] = 'Range Rover Evoque',
    ['brand'] = 'Range Rover',
    ['model'] = 'rrevoque',
    ['price'] = 50000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `rrevoque`,
    ['shop'] = 'pdm',
},
['rsvr16'] = {
    ['name'] = '2016 Range Rover Sport SVR',
    ['brand'] = 'Range Rover',
    ['model'] = 'rsvr16',
    ['price'] = 120000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `rsvr16`,
    ['shop'] = 'pdm',
},

-- ROLLSROYCE
['wraith'] = {
    ['name'] = 'Rolls-Royce Wraith',
    ['brand'] = 'Rolls-Royce',
    ['model'] = 'wraith',
    ['price'] = 300000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `wraith`,
    ['shop'] = 'pdm',
},
['rculi'] = {
    ['name'] = 'Rolls Royce Cullinan',
    ['brand'] = 'Rolls-Royce',
    ['model'] = 'rculi',
    ['price'] = 350000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `rculi`,
    ['shop'] = 'pdm',
},
['rrphantom'] = {
    ['name'] = '2018 Rolls-Royce Phantom VIII',
    ['brand'] = 'Rolls-Royce',
    ['model'] = 'rrphantom',
    ['price'] = 500000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `rrphantom`,
    ['shop'] = 'pdm',
},

-- SUBARU
['subisti08'] = {
    ['name'] = '2008 Subaru WRX STi',
    ['brand'] = 'Subaru',
    ['model'] = 'subisti08',
    ['price'] = 25000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `subisti08`,
    ['shop'] = 'pdm',
},
['subwrx'] = {
    ['name'] = '2004 Subaru Impreza WRX STI',
    ['brand'] = 'Subaru',
    ['model'] = 'subwrx',
    ['price'] = 28000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `subwrx`,
    ['shop'] = 'pdm',
},
['svx'] = {
    ['name'] = '1996 Subaru Alcyone SVX',
    ['brand'] = 'Subaru',
    ['model'] = 'svx',
    ['price'] = 20000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `svx`,
    ['shop'] = 'pdm',
},

-- TOYOTA
['vxr'] = {
    ['name'] = '2016 Toyota Land Cruiser VXR',
    ['brand'] = 'Toyota',
    ['model'] = 'vxr',
    ['price'] = 80000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `vxr`,
    ['shop'] = 'pdm',
},
['mk2100'] = {
    ['name'] = 'Toyota Mark II JZX100',
    ['brand'] = 'Toyota',
    ['model'] = 'mk2100',
    ['price'] = 30000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `mk2100`,
    ['shop'] = 'pdm',
},
['toysupmk4'] = {
    ['name'] = '1998 Toyota Supra Turbo (A80)',
    ['brand'] = 'Toyota',
    ['model'] = 'toysupmk4',
    ['price'] = 60000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `toysupmk4`,
    ['shop'] = 'pdm',
},
['ae86'] = {
    ['name'] = 'Toyota Trueno (AE86)',
    ['brand'] = 'Toyota',
    ['model'] = 'ae86',
    ['price'] = 25000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `ae86`,
    ['shop'] = 'pdm',
},

-- VOLKSWAGEN
['golfgti7'] = {
    ['name'] = '2015 Volkswagen Golf GTI MK7',
    ['brand'] = 'Volkswagen',
    ['model'] = 'golfgti7',
    ['price'] = 30000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `golfgti7`,
    ['shop'] = 'pdm',
},
['passat'] = {
    ['name'] = '2016 Volkswagen Passat B8',
    ['brand'] = 'Volkswagen',
    ['model'] = 'passat',
    ['price'] = 25000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `passat`,
    ['shop'] = 'pdm',
},
['vwr'] = {
    ['name'] = 'Volkswagen Scirocco R 2011',
    ['brand'] = 'Volkswagen',
    ['model'] = 'vwr',
    ['price'] = 28000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `vwr`,
    ['shop'] = 'pdm',
},
['amarok'] = {
    ['name'] = '2018 Volkswagen Amarok V6',
    ['brand'] = 'Volkswagen',
    ['model'] = 'amarok',
    ['price'] = 40000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `amarok`,
    ['shop'] = 'pdm',
},
['golf8gti'] = {
    ['name'] = 'Volkswagen Golf 8 gti',
    ['brand'] = 'Volkswagen',
    ['model'] = 'golf8gti',
    ['price'] = 35000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `golf8gti`,
    ['shop'] = 'pdm',
},

-- VOLVO
['xc90'] = {
    ['name'] = 'Volvo XC90 T8',
    ['brand'] = 'Volvo',
    ['model'] = 'xc90',
    ['price'] = 70000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `xc90`,
    ['shop'] = 'pdm',
},

-- WMOTORS
['wmfenyr'] = {
    ['name'] = 'W-Motors Fenyr Supersport',
    ['brand'] = 'WMotors',
    ['model'] = 'wmfenyr',
    ['price'] = 2500000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `wmfenyr`,
    ['shop'] = 'pdm',
},
['lykan'] = {
    ['name'] = 'W-Motors Lykan HyperSport',
    ['brand'] = 'WMotors',
    ['model'] = 'lykan',
    ['price'] = 3000000,
    ['category'] = 'imports',
    ['categoryLabel'] = 'Imports',
    ['hash'] = `lykan`,
    ['shop'] = 'pdm',
},
