        { model = 'twingo', name = 'Peugeot Twingo', brand = 'Peugeot', price = 10000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'yPG205t16A', name = 'Peugeot 205 Rally', brand = 'Peugeot', price = 15000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'yPG205t16B', name = 'Peugeot 205 Turbo 16', brand = 'Peugeot', price = 18000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'svx', name = '1996 Subaru Alcyone SVX', brand = 'Subaru', price = 20000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'miata3', name = '1989 Mazda Miata NA', brand = 'Mazda', price = 20000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'na6', name = 'Mazda MX-5 Miata (NA6C)', brand = 'Mazda', price = 22000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'ae86', name = 'Toyota Trueno (AE86)', brand = 'Toyota', price = 25000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = '180sx', name = 'Nissan 180SX Type-X', brand = 'Nissan', price = 25000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'fto', name = 'Mitsubishi FTO GP Version-R', brand = 'Mitsubishi', price = 25000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'passat', name = '2016 Volkswagen Passat B8', brand = 'Volkswagen', price = 25000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'subisti08', name = '2008 Subaru WRX STi', brand = 'Subaru', price = 25000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'fc3s', name = 'Mazda RX7 FC3S', brand = 'Mazda', price = 25000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'subwrx', name = '2004 Subaru Impreza WRX STI', brand = 'Subaru', price = 28000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 's14', name = '1998 Nissan Silvia K', brand = 'Nissan', price = 28000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'vwr', name = 'Volkswagen Scirocco R 2011', brand = 'Volkswagen', price = 28000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = '84rx7k', name = '1984 Mazda RX-7 Stanced Version', brand = 'Mazda', price = 30000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'maj350', name = 'Nissan Fairlady Z Z33', brand = 'Nissan', price = 30000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'mk2100', name = 'Toyota Mark II JZX100', brand = 'Toyota', price = 30000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'golfgti7', name = '2015 Volkswagen Golf GTI MK7', brand = 'Volkswagen', price = 30000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'majfd', name = 'Mazda RX-7 FD', brand = 'Mazda', price = 30000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'nis15', name = 'Nissan Silvia S15 Spec-R', brand = 'Nissan', price = 30000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'z32', name = 'Nissan 300ZX Z32', brand = 'Nissan', price = 30000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'Safari97', name = '1997 Nissan Patrol Super Safari Y60', brand = 'Nissan', price = 30000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'ns350', name = 'Nissan 350z Stardast', brand = 'Nissan', price = 35000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'golf8gti', name = 'Volkswagen Golf 8 gti', brand = 'Volkswagen', price = 35000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'cp9a', name = 'Mitsubishi Lancer Evo VI T.M.E (CP9A)', brand = 'Mitsubishi', price = 35000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'sl500', name = '1995 Mercedes-Benz SL500', brand = 'Mercedes-Benz', price = 40000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'nzp', name = 'Nissan 370z "Pandem"', brand = 'Nissan', price = 40000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'dragfd', name = '2002 Mazda RX-7 FD Drag', brand = 'Mazda', price = 40000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'amarok', name = '2018 Volkswagen Amarok V6', brand = 'Volkswagen', price = 40000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'nissantitan17', name = '2017 Nissan Titan Warrior', brand = 'Nissan', price = 40000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'rrevoque', name = 'Range Rover Evoque', brand = 'Range Rover', price = 50000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'skyline', name = 'Nissan Skyline GT-R (BNR34)', brand = 'Nissan', price = 50000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'toysupmk4', name = '1998 Toyota Supra Turbo (A80)', brand = 'Toyota', price = 60000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'levante', name = 'Maserati Levante', brand = 'Maserati', price = 70000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'xc90', name = 'Volvo XC90 T8', brand = 'Volvo', price = 70000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'v250', name = 'Mercedes-Benz V-class 250 Bluetec LWB', brand = 'Mercedes-Benz', price = 70000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = '718caymans', name = 'Porsche 718 Cayman S', brand = 'Porsche', price = 80000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'pcs18', name = '2018 Porsche Cayenne S', brand = 'Porsche', price = 80000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'vxr', name = '2016 Toyota Land Cruiser VXR', brand = 'Toyota', price = 80000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'gl63', name = 'Mercedes-Benz GL63 AMG', brand = 'Mercedes-Benz', price = 85000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'e400', name = '2019 Mercedes-Benz E400 Coupe 4matic (C238)', brand = 'Mercedes-Benz', price = 90000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'mbc63', name = '2012 Mercedes-Benz C63 AMG Coupe Black Series', brand = 'Mercedes-Benz', price = 110000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'rsvr16', name = '2016 Range Rover Sport SVR', brand = 'Range Rover', price = 120000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'c6320', name = '2020 Mercedes-AMG C63s', brand = 'Mercedes-Benz', price = 120000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'gtr', name = '2017 Nissan GTR', brand = 'Nissan', price = 120000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 's500w222', name = '2014 Mercedes-Benz S500 W222', brand = 'Mercedes-Benz', price = 130000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'gtrc', name = '2017 R35 Nissan GTR Convertible', brand = 'Nissan', price = 130000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'G65', name = '2013 Mercedes-Benz G65 AMG', brand = 'Mercedes-Benz', price = 150000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'taycan', name = '2020 Porsche Taycan Turbo S', brand = 'Porsche', price = 150000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'amggtrr20', name = '2020 Mercedes-Benz AMG GT-R Roadster', brand = 'Mercedes-Benz', price = 250000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'wraith', name = 'Rolls-Royce Wraith', brand = 'Rolls-Royce', price = 300000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'ast', name = '2013 Aston Martin Vanquish', brand = 'Aston Martin', price = 300000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'rculi', name = 'Rolls Royce Cullinan', brand = 'Rolls-Royce', price = 350000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'maj935', name = '1978 Porsche 935 Moby Dick', brand = 'Porsche', price = 350000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'rrphantom', name = '2018 Rolls-Royce Phantom VIII', brand = 'Rolls-Royce', price = 500000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'cgt', name = '2003 Porsche Carrera GT (980)', brand = 'Porsche', price = 500000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'mcst', name = '2020 McLaren Speedtail', brand = 'McLaren', price = 2000000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'wmfenyr', name = 'W-Motors Fenyr Supersport', brand = 'WMotors', price = 2500000, category = 'imports', type = 'automobile', shop = 'pdm' },
        { model = 'lykan', name = 'W-Motors Lykan HyperSport', brand = 'WMotors', price = 3000000, category = 'imports', type = 'automobile', shop = 'pdm' },
